name: Merge Bot

on:
  pull_request:


jobs:
  merge:
    if: github.event.pull_request.user.login == 'app-services-ci'
    runs-on: ubuntu-latest
    name: Merge
    steps:
    - name: Wait on checks
        uses: ./
        with:
          ref: ${{ github.sha }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          running-workflow-name: wait-for-check-regexp
          check-regexp: ^(?!.*Merge).*
    - name: Integration check
      uses: squalrus/merge-bot@v0.4.5
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        test: true
        reviewers: false
        checks_enabled: true
        method: squash
        delete_source_branch: true
